settings:
  update-notify: true
  disabled-worlds:
    - example_world
    - example_nether

difficulty-bonus:
  EASY: 0.0
  NORMAL: 10.0
  HARD: 20.0

features:
  equipment:
    enabled: true
    targets:
      - ZOMBIE
      #- DROWNED
      #- HUSK
      #- ZOMBIFIED_PIGLIN

  break-block:
    enabled: true

  rage:
    enabled: true
    duration: 10.0
    effects:
      strength: 1
      speed: 2
    visual:
      particles: true
      sound: true

  tanky:
    enabled: true
    reduction-percentage:
      ZOMBIE: 30.0

  parasite:
    enabled: true
    chance: 35.0
    amount:
      min: 1
      max: 3

  armor-piercing:
    enabled: true
    chance: 15.0
    visual:
      particles: true
      sound: true

  critical-strike:
    enabled: true
    bonus-damage: 50.0
    chance:
      ZOMBIE: 35.0